yarnPath: .yarn/releases/yarn-3.1.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

nodeLinker: node-modules

enableMessageNames: false
