services:
  app:
    image: ciccd/app
    build:
      context: ./
      dockerfile: packages/app/Dockerfile
      # these must be provided by setting a .env file in the root folder
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      target: dev
    
    volumes:
      - .:/app
    
    env_file: ./packages/app/.env
    environment:
      - GITHUB_TOKEN
      - JIRA_USER
      - JIRA_PASSWORD
    
    ports:
      - "3000:3000"

  ciccd-service:
    image: ciccd/ciccd-service
    build:
      context: ./
      dockerfile: packages/ciccd-service/Dockerfile
      target: dev
    
    env_file: ./.env
    environment:
      - GITHUB_TOKEN
      - GCP_PROJECT
      - PORT=8080
    
    ports:
      - "8080:8080"
    volumes:
    - .:/app
    - ${HOME}/.config/gcloud:/root/.config/gcloud
  
  notification-service:
    image: ciccd/notification-service
    build:
      context: ./
      dockerfile: packages/notification-service/Dockerfile
      target: dev
    
    env_file: ./.env
    environment:
      - GITHUB_TOKEN
      - GCP_PROJECT
      - PORT=8081
    
    ports:
      - "8081:8081"

    volumes:
    - .:/app
    - ${HOME}/.config/gcloud:/root/.config/gcloud

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M