env: standard
runtime: nodejs16
service: APP_ENGINE_SERVICE_VALUE
entrypoint: npm run start
handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  JIRA_USER: JIRA_USER_VALUE
  JIRA_PASSWORD: JIRA_PASSWORD_VALUE
  JIRA_HOST: JIRA_HOST_VALUE
  GITHUB_TOKEN: GITHUB_TOKEN_VALUE